import { defineStore } from 'pinia';

interface Wine {
  name: string;
  category: string;
  subcategory?: string;
  type?: string;
}

export const useWineStore = defineStore('wineStore', {
  state: () => ({
    wines: [
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Assyrtiko' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Pinot Blanc' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Cortese' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Roussanne' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Moschofilero' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Muscadet' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Viognier' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Verdicchio' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Greco' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Marsanne' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'White Burgundy' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Chardonnay' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Gruener Veltliner' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'White Rioja' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Frascati' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Gavi' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'L Acadie Blanc' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Trebbiano' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Sauvignon Blanc' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Catarratto' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Albarino' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Arneis' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Verdejo' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Vermentino' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Soave' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Pinot Grigio' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Dry Riesling' },
      { category: 'White Wine', subcategory: 'Dry White Wine', type: 'Torrontes' },
      { category: 'White Wine', subcategory: '', type: 'Mueller Thurgau' },
      { category: 'White Wine', subcategory: '', type: 'Grechetto' },
      { category: 'White Wine', subcategory: '', type: 'Gewurztraminer' },
      { category: 'White Wine', subcategory: '', type: 'Chenin Blanc' },
      { category: 'White Wine', subcategory: '', type: 'White Bordeaux' },
      { category: 'White Wine', subcategory: '', type: 'Semillon' },
      { category: 'White Wine', subcategory: '', type: 'Riesling' },
      { category: 'White Wine', subcategory: '', type: 'Sauternes' },
      { category: 'White Wine', subcategory: '', type: 'Sylvaner' },
      { category: 'White Wine', subcategory: '', type: 'Lillet Blanc' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Petite Sirah' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Zweigelt' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Baco Noir' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Bonarda' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Cabernet Franc' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Bairrada' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Barbera Wine' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Primitivo' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Pinot Noir' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Nebbiolo' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Dolcetto' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Tannat' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Negroamaro' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Red Burgundy' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Corvina' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Rioja' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Cotes Du Rhone' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Grenache' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Malbec' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Zinfandel' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Sangiovese' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Carignan' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Carmenere' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Cesanese' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Cabernet Sauvignon' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Aglianico' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Tempranillo' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Shiraz' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Mourvedre' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Merlot' },
      { category: 'Red Wine', subcategory: 'Dry Red Wine', type: 'Nero D Avola' },
      { category: 'Red Wine', subcategory: '', type: 'Bordeaux' },
      { category: 'Red Wine', subcategory: '', type: 'Marsala' },
      { category: 'Red Wine', subcategory: '', type: 'Port' },
      { category: 'Red Wine', subcategory: '', type: 'Gamay' },
      { category: 'Red Wine', subcategory: '', type: 'Dornfelder' },
      { category: 'Red Wine', subcategory: '', type: 'Concord Wine' },
      { category: 'Red Wine', subcategory: '', type: 'Sparkling Red Wine' },
      { category: 'Red Wine', subcategory: '', type: 'Pinotage' },
      { category: 'Red Wine', subcategory: '', type: 'Agiorgitiko' },
      { category: 'Dessert Wine', subcategory: '', type: 'Pedro Ximenez' },
      { category: 'Dessert Wine', subcategory: '', type: 'Moscato' },
      { category: 'Dessert Wine', subcategory: '', type: 'Late Harvest' },
      { category: 'Dessert Wine', subcategory: '', type: 'Ice Wine' },
      { category: 'Dessert Wine', subcategory: '', type: 'White Port' },
      { category: 'Dessert Wine', subcategory: '', type: 'Lambrusco Dolce' },
      { category: 'Dessert Wine', subcategory: '', type: 'Madeira' },
      { category: 'Dessert Wine', subcategory: '', type: 'Banyuls' },
      { category: 'Dessert Wine', subcategory: '', type: 'Vin Santo' },
      { category: 'Dessert Wine', subcategory: '', type: 'Port' },
      { category: 'Rose Wine', subcategory: '', type: 'Sparkling Rose' },
      { category: 'Sparkling Wine', subcategory: '', type: 'Cava' },
      { category: 'Sparkling Wine', subcategory: '', type: 'Cremant' },
      { category: 'Sparkling Wine', subcategory: '', type: 'Champagne' },
      { category: 'Sparkling Wine', subcategory: '', type: 'Prosecco' },
      { category: 'Sparkling Wine', subcategory: '', type: 'Spumante' },
      { category: 'Sparkling Wine', subcategory: '', type: 'Sparkling Rose' },
      { category: 'Sherry', subcategory: '', type: 'Cream Sherry' },
      { category: 'Sherry', subcategory: '', type: 'Dry Sherry' },
      { category: 'Vermouth', subcategory: '', type: 'Dry Vermouth' },
      { category: 'Fruit Wine', subcategory: '', type: '' },
      { category: 'Mead', subcategory: '', type: '' }
    ] as Wine[]
  }),
  actions: {
    getRandomWine(): Wine {
      const randomIndex = Math.floor(Math.random() * this.wines.length);
      return this.wines[randomIndex];
    }
  }
});
